from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path

from PIL import Image, ImageDraw


PROJECT_ROOT = Path(__file__).resolve().parents[1]
ASSETS_ROOT = PROJECT_ROOT / "assets"
CATALOG_PATH = ASSETS_ROOT / "catalog.json"
LOCAL_ROOT = ASSETS_ROOT / "local"
MARKER_PATH = LOCAL_ROOT / ".demo-assets"


def palette(asset_id: str) -> tuple[tuple[int, int, int, int], tuple[int, int, int, int], bytes]:
    digest = hashlib.sha256(asset_id.encode("utf-8")).digest()
    primary = tuple(64 + value % 160 for value in digest[:3]) + (255,)
    accent = tuple(48 + value % 176 for value in digest[3:6]) + (255,)
    return primary, accent, digest


def draw_placeholder(asset_id: str, frame_index: int = 0) -> Image.Image:
    primary, accent, digest = palette(asset_id)
    image = Image.new("RGBA", (160, 192), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    shift = frame_index * 6
    left = 20 + shift
    top = 24 + digest[6] % 12
    right = 140 + shift
    bottom = 154
    draw.rounded_rectangle(
        (left, top, right, bottom),
        radius=22,
        fill=primary,
        outline=(24, 24, 30, 255),
        width=4,
    )
    draw.polygon(
        ((left + 18, top + 20), (left + 44, top - 12), (left + 58, top + 24)),
        fill=accent,
        outline=(24, 24, 30, 255),
    )
    for index, value in enumerate(digest[7:15]):
        x = left + 12 + index * 12
        height = 10 + value % 28
        draw.rectangle((x, bottom - height, x + 7, bottom - 8), fill=accent)
    draw.text((10, 171), asset_id[:24], fill=(24, 24, 30, 255))
    return image


def reset_demo_root() -> None:
    if not LOCAL_ROOT.exists():
        return
    if not MARKER_PATH.is_file():
        raise RuntimeError(
            "assets/local 已包含非演示素材；demo:assets 不会覆盖该目录"
        )
    shutil.rmtree(LOCAL_ROOT)


def generate_static(asset_id: str, output_root: Path) -> None:
    draw_placeholder(asset_id).save(output_root / f"{asset_id}.png", format="PNG")


def generate_animated(asset_id: str, output_root: Path) -> None:
    frames = [draw_placeholder(asset_id, index) for index in range(3)]
    frames[0].save(
        output_root / f"{asset_id}.gif",
        format="GIF",
        save_all=True,
        append_images=frames[1:],
        duration=[90, 120, 150],
        loop=0,
        disposal=2,
    )


def main() -> None:
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    static_ids = list(catalog["staticAssets"])
    animated_ids = list(catalog["animatedAssets"])

    reset_demo_root()
    static_root = LOCAL_ROOT / "static"
    animated_root = LOCAL_ROOT / "animated"
    static_root.mkdir(parents=True)
    animated_root.mkdir(parents=True)
    MARKER_PATH.write_text("generated by scripts/generate_demo_assets.py\n", encoding="utf-8")

    for asset_id in static_ids:
        generate_static(asset_id, static_root)
    for asset_id in animated_ids:
        generate_animated(asset_id, animated_root)

    print(f"Demo assets generated: {len(static_ids)} PNG, {len(animated_ids)} GIF")


if __name__ == "__main__":
    main()
