(function attachPetDialogue(root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) {
    module.exports = api;
  }
  if (root) {
    root.PetDialogue = api;
  }
})(typeof globalThis !== "undefined" ? globalThis : this, function createPetDialogue() {
  const PRIMARY_DIALOGUE = Object.freeze({
    "love": ["最喜欢你啦！", "给你比个心～"],
    "sign-nb": ["这波操作，真nb！", "倒着也要夸你一句nb！"],
    "sign-qu": ["蛆！是一只小蛆！", "今日限定：糖猫蛆。"],
    "street-stall": ["走过路过，看看嘛～"],
    "electrocuted": ["酥酥麻麻的！"],
    "color-shock": ["等等，真的假的！"],
    "embarrassed": ["嘿嘿，有点不好意思。"],
    "not-drooling": ["我才没有馋！"],
    "dry-tears": ["擦干眼泪，重新出发！", "好啦，我已经不难过了。"],
    "wipe-tears": ["没事，我缓一会儿。"],
    "rainbow-vomit": ["彩虹……也不是这么吐的！"],
    "too-loud": ["小声一点嘛！"],
    "sleep-after-meal": ["吃饱了就该睡觉。"],
    "meal-1": ["开饭啦！"],
    "meal-2": ["这口是我的～"],
    "meal-3": ["再来一口！"],
    "meal-4": ["好吃得停不下来。"],
    "eat-fish": ["今天有鱼吃！"],
    "hammer": ["这一锤很有分量！"],
    "sale": ["限时好价，快来看看！"],
    "rub-hands": ["嘿嘿，让我期待一下。"],
    "paws-tucked": ["小手一揣，谁也不爱。", "今天先做一只冷酷小猫。"],
    "gaming": ["这局一定能赢！"],
    "gaming-1": ["别急，我在操作。"],
    "gaming-2": ["就差一点点！"],
    "gaming-3": ["再来一局！"],
    "greeting": ["嗨，见到你真好～"],
    "big-bite": ["嘴巴张大，开吃！", "嗷呜，一口拿下！"],
    "big-bite-fish": ["好大一口鱼！"],
    "stylish": ["今天也很有派头。"],
    "headphones": ["让我听听这首～"],
    "headphones-1": ["正在听喜欢的歌♪"],
    "headphones-2": ["这个节奏不错！"],
    "headphones-3": ["先沉浸一会儿～"],
    "one-leg-stand": ["看我站得稳不稳？"],
    "smug": ["哼哼，我厉害吧！"],
    "subway-phone": ["再看一小会儿手机。"],
    "iv-drip": ["今天要乖乖休息。"],
    "hide": ["你看不见我～"],
    "dodge": ["先躲一下！"],
    "goose": ["这位朋友有点凶。"],
    "fall-over": ["哎呀，翻过去了！"],
    "magnify": ["让我仔细看看。"],
    "give-up": ["算啦，先歇一会儿。"],
    "awkward": ["当作什么都没发生……"],
    "kung-fu": ["看招！糖猫功夫！"],
    "seal": ["啪嗒啪嗒～"],
    "seal-1": ["今天是一只海豹猫。"],
    "seal-2": ["翻个面继续躺。"],
    "seal-3": ["海豹模式启动！"],
    "good-chance": ["好机会，冲呀！"],
    "red-hot": ["脸、脸怎么热起来了！"],
    "panic": ["等一下，先别慌！"],
    "game-over": ["完了，这局真的寄啦！", "小纸箱已经准备好了。"],
    "startled": ["吓我一跳！"],
    "surprised": ["咦？居然是这样！"],
    "salute": ["收到！交给我吧！"],
    "refuse": ["不要，我拒绝。"],
    "handstand": ["世界怎么倒过来了？", "换个角度看看你！"],
    "flying": ["芜湖，起飞！", "糖猫航班出发啦！"],
    "confused": ["看不懂喵……"],
    "confused-2": ["我再眯眼看看……", "看懂了吗？反正我没有。"],
    "phone": ["让我看看新消息。"],
    "phone-complete": ["认真刷一会儿～"],
    "phone-2": ["手机里有什么呢？"],
    "read-book": ["安静看会儿书。"],
    "bite-tail-cry": ["尾巴也不能解决烦恼……"],
    "soul": ["我的灵魂飘走了……"],
    "messy-1": ["脑袋一歪，思路全乱啦！", "等等，我好像转反了。"],
    "messy-2": ["我是谁，我该往哪边走？", "尾巴都比脑子清醒。"],
    "drool": ["吸溜……看起来好香。"],
    "numb": ["彻底麻了。"],
    "shopping": ["喜欢就带回家！"],
    "full": ["吃得圆滚滚～"],
    "steering-wheel": ["坐稳啦，要出发咯！"],
    "swallow-1": ["我先尝一小口。"],
    "swallow-2": ["嗷呜，一口吞掉！"],
    "touch-bird-egg-1": ["轻轻摸一下。"],
    "touch-bird-egg-2": ["里面会是什么呢？"],
    "sunglasses": ["酷猫登场。"],
    "shout": ["啊——我有话要说！", "听见我的呐喊了吗！"],
    "prone-1": ["趴一小会儿。"],
    "prone-2": ["地上凉凉的。"],
    "prone-3": ["今天不想动啦。"],
    "prone-4": ["再躺五分钟。"],
    "prone-5": ["再趴一会儿，就一会儿。", "地板今天格外有吸引力。"],
    "prone-rise": ["趴下……再努力爬起来！", "让我缓缓，我还能起。"],
    "auction": ["这件宝贝，谁要？"],
    "hand-wave": ["看我潇洒一挥！", "小手一抛，烦恼拜拜！"],
    "butt-1": ["给你看个背影。"],
    "butt-2": ["尾巴藏好了吗？"],
    "pounce": ["抓到你啦！"],
    "ride-crocodile": ["鳄鱼号，出发！"],
    "knight": ["糖猫骑士前来守护！"],
    "sunny-doll": ["明天也要是晴天。"],
    "poor": ["口袋空空，心态稳稳。", "今天也是节俭小猫。"],
    "dead": ["我先安详地躺一下……"],
    "fully-equipped": ["装备齐全，准备出发！"],
    "reach": ["手给我，贴一下～"],
    "long-reach": ["再远也能碰到你！"],
    "lion-1": ["嗷呜——"],
    "lion-2": ["威风的小狮子来啦！"],
    "lion-3": ["其实一点也不凶。"],
    "recycling": ["旧东西也能变宝贝。"],
    "comfortable": ["好舒服呀～"],
    "arms-crossed": ["让我认真想想。"],
    "sleep": ["呼……晚安。"],
    "sleep-wake": ["我醒了……好像又没醒。", "起床失败，倒头就睡。"],
    "send-flower": ["这朵花送给你！"],
    "recliner": ["这才叫享受～"],
    "observe-lying": ["躺着也能看得很清楚。"],
    "jump": ["跳一下，心情变好！"],
    "eavesdrop": ["我好像听见了什么……"],
    "vomit": ["呜哇——不可以吃这个！"],
    "wow": ["哇！好厉害！"],
    "maimai-1": ["要开始了哟！", "不要大力拍打或滑动哦！"],
    "maimai-2": ["不可以打我哟！", "这颗绝赞我接住啦！"],
    "calling": ["喂——听得到吗？"],
    "writing": ["认真写点东西。"],
    "flex": ["看看我的力量！"],
    "excited-tasting": ["让我先尝一口！", "嗯嗯，就是这个味！"],
    "bluff": ["我、我可是很凶的！"],
    "puzzled": ["嗯？这是为什么？"],
    "standing-wave": ["我在这里呀～"],
    "photo": ["看镜头，三、二、一！", "这张一定要拍得可爱！"],
    "wisdom": ["让我用智慧想一想。"],
    "crawl": ["糖猫蛆正在接近……", "扭一扭就能前进！"],
    "bird": ["啾，今天由我站岗。", "屋檐下躲一会儿雨。"],
  });

  const SECONDARY_DIALOGUE = Object.freeze({
    "street-stall": "小摊开张，今天也营业！",
    "electrocuted": "毛都要竖起来了！",
    "color-shock": "震惊到颜色都变了！",
    "embarrassed": "刚才那个不算啦。",
    "not-drooling": "只是嘴角有自己的想法。",
    "wipe-tears": "风太大，眼睛进沙啦。",
    "rainbow-vomit": "这画面是不是太绚丽了？",
    "too-loud": "耳朵要受不了啦！",
    "sleep-after-meal": "肚子饱饱，眼皮沉沉。",
    "meal-1": "第一口最香！",
    "meal-2": "谁也别抢我的饭。",
    "meal-3": "碗里怎么又空了？",
    "meal-4": "最后一口，真的！",
    "eat-fish": "鱼鱼，我来啦！",
    "hammer": "哪里不服锤哪里！",
    "sale": "错过今天，再等今天！",
    "rub-hands": "好东西是不是要来了？",
    "gaming": "胜负就在这一把！",
    "gaming-1": "手柄可不能松！",
    "gaming-2": "队友快跟上呀！",
    "gaming-3": "输了不算，再开！",
    "greeting": "今天也来陪你啦！",
    "big-bite-fish": "一口就要吃过瘾！",
    "stylish": "这气场，够不够排面？",
    "headphones": "外面的声音先暂停。",
    "headphones-1": "这一段要单曲循环。",
    "headphones-2": "忍不住跟着摇啦♪",
    "headphones-3": "谁也别打断副歌！",
    "one-leg-stand": "这可是平衡训练。",
    "smug": "夸我，我听着呢～",
    "subway-phone": "坐过站也不能怪手机。",
    "iv-drip": "今天是病号猫。",
    "hide": "这里绝对很隐蔽。",
    "dodge": "差一点就被发现啦！",
    "goose": "惹不起，真的惹不起。",
    "fall-over": "谁来帮我翻个面？",
    "magnify": "细节里一定有答案。",
    "give-up": "努力过了，可以躺了。",
    "awkward": "脚趾已经开始施工了。",
    "kung-fu": "这一招叫猫猫拳！",
    "seal": "今天只想拍肚皮。",
    "seal-1": "海豹猫也要晒太阳。",
    "seal-2": "这面躺得有点麻。",
    "seal-3": "圆滚滚才是本体。",
    "good-chance": "机不可失，猫不再来！",
    "red-hot": "再说就要冒烟啦！",
    "panic": "我的镇定跑哪去了？",
    "startled": "心跳漏了一拍！",
    "surprised": "我的眼睛不会骗人！",
    "salute": "糖猫保证完成任务！",
    "refuse": "这件事没得商量。",
    "confused": "每个字都认识，合起来不会。",
    "phone": "没有玩，只是在回消息。",
    "phone-complete": "再刷一个就放下。",
    "phone-2": "屏幕里藏着什么秘密？",
    "read-book": "这一页马上就看完。",
    "bite-tail-cry": "越想越委屈了……",
    "soul": "身体留下，灵魂下班。",
    "drool": "香味已经把我抓住了。",
    "numb": "大脑已停止响应。",
    "shopping": "购物车又自己变满了！",
    "full": "肚皮已经没有空位。",
    "steering-wheel": "下一站，快乐老家！",
    "swallow-1": "就尝一下，不算偷吃。",
    "swallow-2": "这一口也太满足了！",
    "touch-bird-egg-1": "它会不会动一下？",
    "touch-bird-egg-2": "千万别把它吵醒。",
    "sunglasses": "不用介绍，我就是焦点。",
    "prone-1": "地板今天格外亲切。",
    "prone-2": "换个姿势继续趴。",
    "prone-3": "电量不足，原地充电。",
    "prone-4": "谁也别劝我起来。",
    "auction": "价高者得，喵槌落定！",
    "butt-1": "正面暂时停止营业。",
    "butt-2": "这个角度也很可爱吧？",
    "pounce": "看准目标，起飞！",
    "ride-crocodile": "今天的坐骑有点硬。",
    "knight": "请躲在本骑士身后！",
    "sunny-doll": "把乌云统统赶走吧。",
    "dead": "有事请烧小鱼干。",
    "fully-equipped": "这套装备够专业吧？",
    "reach": "不许走，先牵手。",
    "long-reach": "手长就是这么方便。",
    "lion-1": "这声吼够威风吗？",
    "lion-2": "草原之王也要卖萌。",
    "lion-3": "吼完了，可以摸摸。",
    "recycling": "瓶瓶罐罐都交给我。",
    "comfortable": "再这样待一会儿嘛。",
    "arms-crossed": "这事得从长计议。",
    "sleep": "梦里有吃不完的鱼。",
    "send-flower": "收下就不许退回来～",
    "recliner": "忙碌暂停，享受开始。",
    "observe-lying": "这个视角别有发现。",
    "jump": "烦恼都被我跳掉啦！",
    "eavesdrop": "再靠近一点就听清了。",
    "vomit": "这口味超出承受范围！",
    "wow": "眼睛都要亮起来了！",
    "calling": "信号不好，再说一遍？",
    "writing": "这一笔要写漂亮。",
    "flex": "别小看糖猫的力量！",
    "bluff": "你再过来我就……跑！",
    "puzzled": "问号已经长出来了。",
    "standing-wave": "看到我就挥挥手吧～",
    "wisdom": "答案正在脑袋里发芽。",
  });

  const EXTRA_DIALOGUE = Object.freeze({
    "love": ["今天也分你一颗心！", "最最喜欢你啦～"],
    "sign-nb": ["举牌认证：你最牛！", "今天的你，属实厉害！"],
    "sign-qu": ["举牌声明：是蛆不是去！", "看清楚啦，qu就是蛆！"],
    "street-stall": ["糖猫小铺，童叟无欺！", "来都来了，挑一个嘛。"],
    "electrocuted": ["啪叽，电量瞬间满格！", "谁在给我充电呀？"],
    "color-shock": ["惊讶到失去原色！", "这个消息太突然啦！"],
    "embarrassed": ["被你发现啦，嘿嘿。", "让我先害羞三秒。"],
    "not-drooling": ["这只是普通的水珠！", "香归香，我忍得住。"],
    "dry-tears": ["纸巾一收，又是好猫。", "眼泪退场，笑容回来！"],
    "wipe-tears": ["眼泪擦掉，又是好猫。", "借我一小张纸巾嘛。"],
    "rainbow-vomit": ["这彩虹有点上头！", "下次不乱吃颜料了。"],
    "too-loud": ["音量旋钮在哪里呀？", "糖猫的耳朵在抗议！"],
    "sleep-after-meal": ["饭后小睡最幸福。", "先睡一觉再消食。"],
    "meal-1": ["今天也要好好吃饭！", "饭香已经飘过来啦。"],
    "meal-2": ["这一碗谁都不许动！", "护食模式启动。"],
    "meal-3": ["再添半碗不过分吧？", "吃饭怎么会嫌多呢。"],
    "meal-4": ["碗底都要舔干净！", "好吃到忘记停筷。"],
    "eat-fish": ["小鱼干请排队入场！", "闻到鱼香就精神啦。"],
    "hammer": ["喵槌出击，咚！", "问题不大，锤一下。"],
    "sale": ["糖猫推荐，绝不踩雷！", "买不了吃亏，快看看。"],
    "rub-hands": ["好戏马上开场啦。", "小手一搓，期待加倍！"],
    "paws-tucked": ["有事请说，我揣手听着。", "气势到位，爪子收好。"],
    "gaming": ["看我极限翻盘！", "这把状态特别好。"],
    "gaming-1": ["操作拉满，别眨眼！", "键位都被我按热啦。"],
    "gaming-2": ["只差最后一下啦！", "稳住，胜利就在前面。"],
    "gaming-3": ["刚才只是热身局。", "不赢一把不下线！"],
    "greeting": ["糖猫准时来报到！", "你好呀，今天开心吗？"],
    "big-bite": ["这口必须吞干净！", "吃到整只猫都膨胀啦！"],
    "big-bite-fish": ["鱼尾巴都别想逃！", "这一口超级满足。"],
    "stylish": ["气势这块拿捏住了。", "出场必须有排面！"],
    "headphones": ["耳机一戴，谁也不爱。", "让我躲进音乐里吧。"],
    "headphones-1": ["这首歌正合我心意！", "旋律在耳朵里打转。"],
    "headphones-2": ["踩准节拍，摇一摇～", "低音一响，猫猫登场。"],
    "headphones-3": ["副歌来了，安静听！", "再循环亿遍就好。"],
    "one-leg-stand": ["金猫独立，稳稳的！", "另一只脚正在休假。"],
    "smug": ["尾巴都要翘上天啦！", "优秀得有点藏不住。"],
    "subway-phone": ["下一站到了再提醒我。", "通勤时间当然要刷屏。"],
    "iv-drip": ["输点元气，马上恢复。", "休息一下就有精神啦。"],
    "hide": ["嘘，我是一团空气。", "藏得这么好找不到吧？"],
    "dodge": ["先闪为敬，溜啦！", "危险靠近，紧急回避。"],
    "goose": ["大鹅请冷静一点！", "这场面我先撤了。"],
    "fall-over": ["四脚朝天也很可爱。", "地面怎么突然转啦？"],
    "magnify": ["目标锁定，认真研究。", "再小的线索也逃不掉。"],
    "give-up": ["今天的努力额度用完啦。", "摆烂五分钟就回来。"],
    "awkward": ["空气忽然安静了。", "现在逃跑还来得及吗？"],
    "kung-fu": ["接我一招喵喵掌！", "武林萌主就是我。"],
    "seal": ["肚皮拍得啪啪响！", "圆滚滚地休息一下。"],
    "seal-1": ["海豹猫开始晒肚皮。", "今天也要软乎乎。"],
    "seal-2": ["左边躺完换右边。", "翻面才能晒得均匀。"],
    "seal-3": ["海豹猫正在登陆！", "请欣赏我的拍肚皮。"],
    "good-chance": ["时机正好，不能错过！", "就是现在，快出手！"],
    "red-hot": ["温度计要爆表啦！", "先让我冷静降温。"],
    "panic": ["手忙脚乱模式开启！", "深呼吸，问题不大。"],
    "game-over": ["别急，我还能抢救一下！", "今日猫生，暂时结算。"],
    "startled": ["毛毛都被吓蓬啦！", "是谁突然冒出来呀？"],
    "surprised": ["嘴巴都合不上啦！", "这也太出乎意料了。"],
    "salute": ["糖猫小队前来报到！", "保证认真站好这一班。"],
    "refuse": ["摇头就是我的答案。", "这回撒娇也没用哦。"],
    "handstand": ["倒着也要卖个萌～", "我在练习猫猫倒立！"],
    "flying": ["今天的风很适合飞行～", "看我飞过来！"],
    "confused": ["知识从脑袋旁边路过。", "能不能再讲一遍呀？"],
    "confused-2": ["这题是不是超纲了？", "让我假装已经明白。"],
    "phone": ["马上回完这条消息。", "屏幕怎么这么好看呢。"],
    "phone-complete": ["最后一个视频，保证！", "手机先替我保管时间。"],
    "phone-2": ["再亮一会儿屏幕嘛。", "让我看看今天的热闹。"],
    "read-book": ["书里好像藏着小鱼干。", "嘘，正看到精彩处呢。"],
    "bite-tail-cry": ["尾巴都陪我一起难过。", "委屈得只好咬尾巴。"],
    "soul": ["灵魂正在外出散步。", "本人暂时不在身体里。"],
    "messy-1": ["今天的方向感离家出走。", "让我先把自己理顺一下。"],
    "messy-2": ["越想越乱，先发会儿呆。", "糟糕，思路打成结啦！"],
    "drool": ["口水比意志更诚实。", "再看一眼就要开吃啦。"],
    "numb": ["整只猫都卡住了。", "今日份无语已送达。"],
    "shopping": ["这个也要，那个也要！", "钱包先闭上眼睛吧。"],
    "full": ["饱到只能慢慢滚啦。", "下一顿请晚点再来。"],
    "steering-wheel": ["糖猫司机准备发车！", "导航说前方有小鱼干。"],
    "swallow-1": ["小口小口才不算贪吃。", "味道不错，再试一点。"],
    "swallow-2": ["一口下去什么都没啦！", "吞咽速度满分。"],
    "touch-bird-egg-1": ["圆乎乎的，手感真好。", "我就摸一下，不拿走。"],
    "touch-bird-egg-2": ["蛋壳里面有动静吗？", "轻一点，别惊到它。"],
    "sunglasses": ["墨镜一戴，气场全开。", "今天走酷猫路线。"],
    "shout": ["糖猫高音，穿透桌面！", "啊啊啊啊啊——"],
    "prone-1": ["地板把我牢牢吸住了。", "趴着也算认真休息。"],
    "prone-2": ["凉凉的地面最舒服。", "这块位置归我啦。"],
    "prone-3": ["今日运动量已经达标。", "一动不动也是本事。"],
    "prone-4": ["五分钟之后再五分钟。", "起床计划暂时取消。"],
    "prone-5": ["起不来，完全起不来。", "这块地方被我承包啦。"],
    "prone-rise": ["起床进度正在反复横跳。", "刚趴稳，怎么又要起来？"],
    "auction": ["第一次，第二次，喵！", "心动的话就举爪吧。"],
    "hand-wave": ["给你甩个小猫爪～", "不管啦，先挥两下！"],
    "butt-1": ["只开放背面参观哦。", "转过去假装没看见。"],
    "butt-2": ["尾巴是今天的主角。", "背影也要保持可爱。"],
    "pounce": ["一二三，猫猫起飞！", "这次一定扑个正着。"],
    "ride-crocodile": ["鳄鱼坐骑请慢一点！", "乘风破浪出发咯。"],
    "knight": ["拔剑吧，糖猫骑士！", "荣誉与小鱼干同在。"],
    "sunny-doll": ["太阳公公快来上班。", "愿明天没有一朵乌云。"],
    "poor": ["再翻也翻不出一枚硬币。", "穷得只剩下可爱啦！"],
    "dead": ["猫猫暂时停止运行。", "躺平之后感觉好多了。"],
    "fully-equipped": ["背包检查完毕，出发！", "从头到脚都准备好啦。"],
    "reach": ["把你的手借我一下。", "击个掌再放你走～"],
    "long-reach": ["远一点也拦不住我。", "橡皮糖猫伸手成功！"],
    "lion-1": ["听见本狮的吼声了吗？", "嗷完就要奖励小鱼干。"],
    "lion-2": ["鬃毛一甩，威风登场！", "小狮子也有大气势。"],
    "lion-3": ["凶完这一秒就撒娇。", "其实我只会软绵绵。"],
    "recycling": ["纸箱瓶子都别浪费。", "糖猫回收站开工啦！"],
    "comfortable": ["舒服得尾巴都放松啦。", "这一刻谁也别打扰。"],
    "arms-crossed": ["让我再观察一会儿。", "这件事值得认真审视。"],
    "sleep": ["呼噜声已经准备好了。", "帮我把月亮关一下。"],
    "sleep-wake": ["被窝说不许我走。", "刚醒，再睡一小会儿。"],
    "send-flower": ["花花和好心情都给你。", "今天也要像花一样开心。"],
    "recliner": ["阳光、躺椅，正合适。", "今天的休闲指标达成。"],
    "observe-lying": ["低处也有新风景。", "我躺着，你继续表演。"],
    "jump": ["蹦一下就充满元气！", "看我跳得高不高？"],
    "eavesdrop": ["嘘，秘密快要听清啦。", "我只是碰巧路过这里。"],
    "vomit": ["味觉正在紧急报警！", "快给我一口清水呀。"],
    "wow": ["这个也太精彩啦！", "让我再惊叹一次，哇！"],
    "maimai-1": ["Let's go!!!", "今天也要冲个鸟加！"],
    "maimai-2": ["转圈拍键，忙不过来啦！", "新纪录！大神降临！"],
    "calling": ["糖猫呼叫，收到请回答！", "喂喂，麦克风测试。"],
    "writing": ["横平竖直，认真落笔。", "今天也写得漂漂亮亮。"],
    "flex": ["小小胳膊，大大力量！", "看见这块猫猫肌了吗？"],
    "excited-tasting": ["舌头先替我验个货。", "好吃得眼睛都亮啦！"],
    "bluff": ["气势先摆足再说！", "别拆穿，我真的很凶。"],
    "puzzled": ["问号正在头顶排队。", "这个问题有点绕呀。"],
    "standing-wave": ["挥挥小手，烦恼走开！", "站好啦，向你问个好。"],
    "photo": ["咔嚓，糖猫今日留影。", "等一下，我还没摆好！"],
    "wisdom": ["聪明的小灯泡亮啦！", "糖猫大脑高速运转中。"],
    "crawl": ["今天也在努力蠕动。", "长条猫悄悄爬过来啦。"],
    "bird": ["这根横杆归我啦。", "我只是一只路过的小鸟。"],
  });

  const ACTION_DIALOGUE = Object.freeze(
    Object.fromEntries(
      Object.entries(PRIMARY_DIALOGUE).map(([name, messages]) => {
        const pair =
          messages.length >= 2
            ? messages.slice(0, 2)
            : [messages[0], SECONDARY_DIALOGUE[name]];
        return [name, Object.freeze([...pair, ...EXTRA_DIALOGUE[name]])];
      }),
    ),
  );

  const OPENING_DIALOGUE = Object.freeze([
    "糖猫今天也来陪你一起摸鱼啦！",
    "新的一天，请多关照这只小糖猫哦！",
    "我来啦，今天也负责把你逗开心！",
    "桌面巡逻开始，有需要就摸摸我吧！",
  ]);

  function messagesForAction(dialogueId) {
    const messages = ACTION_DIALOGUE[dialogueId];
    if (!messages) throw new Error(`普通动作缺少气泡文案：${dialogueId}`);
    return messages;
  }

  function dialogueForAction(dialogueId, random = Math.random) {
    const messages = messagesForAction(dialogueId);
    const index = Math.min(
      messages.length - 1,
      Math.floor(Math.max(0, Math.min(0.999999, random())) * messages.length),
    );
    return messages[index];
  }

  function bubbleMessageForAction(dialogueId, random = Math.random) {
    return dialogueForAction(dialogueId, random);
  }

  function openingDialogueForLaunch(random = Math.random) {
    const index = Math.min(
      OPENING_DIALOGUE.length - 1,
      Math.floor(
        Math.max(0, Math.min(0.999999, random())) * OPENING_DIALOGUE.length,
      ),
    );
    return OPENING_DIALOGUE[index];
  }

  return {
    ACTION_DIALOGUE,
    OPENING_DIALOGUE,
    bubbleMessageForAction,
    dialogueForAction,
    messagesForAction,
    openingDialogueForLaunch,
  };
});
